# https://taskfile.dev

version: "3"

vars:
  VAULT: hirn

  DIR_PLUGIN: C:\PROJECTS\Obsidian\{{.VAULT}}\.obsidian\plugins\webdav

  # USER_WORKING_DIR: C:\PROJECTS\Obsidian\{{.VAULT}}

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task: build
      - task: copy
  copy:
    cmds:
      - xcopy "{{.USER_WORKING_DIR}}\main.js" "{{.DIR_PLUGIN}}\main.js" /Y
      - xcopy "{{.USER_WORKING_DIR}}\styles.css" "{{.DIR_PLUGIN}}\styles.css" /Y
  build:
    cmds:
      - npm run build
  patch:
    cmds:
      - npm version patch
  git:
    cmds:
      - git add .
      - git commit -m "task"
      - git push
  test:
    cmds:
      - npm test -env-file .env
  research:
    cmds:
      - node tests/exclude/research.js
  minify:
    cmds:
      - terser main.js -o main.min.js
  time:
    cmds:
      - date +%T
